name: Main pipeline

on: [push, pull_request]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: print platform
        run: code "Code is OK"
  test:
    strategy:
      matrix:
        go-version: [1.18.x, 1.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code
        uses: actions/checkout@v3

      - name: print platform
        run: echo "Tests are GREEN in ${{ matrix.platform }}"
